FF1Lib/FF1Rom.cs, FF1Lib/Maps.cs
The early-access to the Castle of Ordeals was, incorrectly, a part of the Shuffle Ordeals flag. As a result, the Early Ordeals convenience was useless, and one could always access the dungeon early if its teleporters were being shuffled.
=> [#31] Fix early ordeals flag not being used.

FF1Lib/Hacks.cs
This patch allows multiple levels to be gained at the end of combat.  Due to the size of the new code required, part of the stat increase message display routine had to be overwritten and therefore this is patch also skips stat messages other than max HP.  Commented ASM source for the patch is as follows:
```
JSR $9F57 ;undraw all battle boxes
PHA ;maybe not needed
LDA $80 ;check if pointer to exp was changed
AND #$7
CMP #$7
BEQ LevelLoop
LDA $80 ;reset exp pointer
AND #$F0
ADC #$7
STA $80
LevelLoop:
PLA 
JSR $9C01 ;get exp to lvlup
JMP $9BE8
```
=> Gain multiple levels at once added to speed hacks.

FF1RandomizerOnline/Views/Home/Randomize.cshtml
It was triggering the EarlyRod box instead. Clicking the EarlyOrdeals
checkbox directly still worked so this is pretty minor.
=> Fix EarlyOrders label click.

FF1Lib/FF1Rom.cs
Both are black but 0x0D seems to be less supported and causes lag.
A little extra checking and loading to use the following colors: 01-0C, then skip to 0F, then back to 01.
=> Fix BG Color to use 0x0F for black, not 0x0D.

FF1Lib/Fun.cs
It would allow you to select the spaces below RUN. It still just
ran like the vanilla game but it was pretty ugly. Thanks to sbq92
for finding this one.
=> ModernBattlefield V2.0 Bugfix.

FF1Lib/BugFixes.cs, FF1Lib/FF1Rom.cs, FF1Lib/Magic.cs
Changes the the following:
AND #$38               ;  this effectively makes A the spell level * 8
ORA ch_spells, X       ; then ORA with the selected spell on this level
CLC                    ; and add the spell start constant - 1 (-1 because 0 is not a spell)
ADC #MG_START-1
to:
AND #$38               ;  this effectively makes A the spell level * 8
CLC
ADC ch_spells, X       ; then ADC with the selected spell on this level  (this will never set the carry flag)
ADC #MG_START-1      ; and add the spell start constant - 1 (-1 because 0 is not a spell)
the comment in the dissassembly describes this well:
; BUGGED:  it just so happens that this code bug never occured in game because the spells
;  were arranged in a way where it wouldn't be a problem.  HOWEVER.  The problem here lies
;  in …
=> Allows warp to be used if in the last spell slot

FF1Lib/FF1Rom.cs
Changes INT. to MDEF in the status menu (and anywhere else that string is used), changes the address to the byte where MDEF is stored, specifically for the status menu
=> Changed INT. to MDEF in the status menu

FF1Lib/FF1Rom.cs, FF1Lib/Fun.cs
It looks like MB removes enough code that it speeds the game up
a frame. In order to keep the overall speed the same and keep the
RNG in lock step with the vanilla game we introduce a wait for
vblank.
=> Add a frame into Modern Battlefield initialization.

FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/Scale.cs
Removes the price reduction for the CRYSTAL and replaces it with scaling the price of the incentive item, based on wherever the item is. It defaults to Coneria being 1/8th of normal price, and Pravoka being 1/2, but this is changable.
I haven't implemented it as a flag since the Crystal being 1/8th price wasn't implemented as a flag, and I don't see "making a seed take forever because you have to grind Ogres or some shit" as an enjoyable option.
=> Caravan item price based on location

FF1Lib/OverworldMap.cs
It seemed like a good idea at the time, but dungeons with a blue sky forest look silly.
"Marsh" has a black sky and could be in some dank ass dungeon.
=> Don't use blue-sky backdrops for dungeons.

FF1Lib/ItemPlacement.cs
Item placement now will check to see if Free Bridge is on before placing the bridge in its limited spots, and if it is... instead it won't. There should probably be another change to this to make sure it doesn't put it in incentive spots either, but this will solve some silliness.
=> Bridge shouldn't get special placement if we already have it

FF1Lib/Flags.cs, FF1Lib/Interfaces.cs, FF1Lib/ItemPlacement.cs, FF1RandomizerOnline/Views/Home/Randomize.cshtml
This adds an option to shuffle 'notable treasure' into a subset of
trapped treasure chests. The list of both the items and locations is a
best first attempt, but should be refined with more
experience/playtesting.
=> Add an option to improve trapped chests

FF1Lib/Enemies.cs, FF1Lib/FF1Rom.cs, FF1Lib/Maps.cs, FF1RandomizerOnline/Views/Home/Randomize.cshtml
Many WarMECHs have escaped the Sky Castle and are now roaming the entire world. 
The first encounter in each zone is removed, encounter 2 through 6 are shifted up one position, the eighth encounter remains last, and WarMech is always in position 7. However, this can still be shuffled by formation shuffle if that option is set to "Shuffle Encounter Rarity".
=> Add Unleashed to WarMECH Modes

.circleci/config.yml
Because "CIRCLE_BRANCH" is the name of the branch being built, and
because github PRs are done from branches such as "pull/1", the if/else
logic to check for building alpha doesn't work.
Since this file is in the alpha branch, and alpha no longer includes the
FF1RandomizerOnline project, it makes sense to remove it from the build
step at least.
=> Fix Circle CI.

FF1Blazorizer/Pages/Randomize.cshtml
"House Full HP Restoration" was using the same flag as "House MP
Restoration" in Blazor. This fixes the flag that's used to be the
correct one.
=> Fix "House HP" Refill toggle.

Enemizer FAQ.txt, FF1Blazorizer/Pages/Randomize.cshtml, FF1Lib/BugFixes.cs, FF1Lib/Enemies.cs, FF1Lib/Enemizer.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs
This is the enemizer update that finally, well, enemizes.  It adds the option to create totally new enemies.
I also included a fix for the Zozo Melmond issue that occurs in the current alpha, and enabling any part of Enemizer will disable shuffling formations, shuffling trap tiles, and fun% enemy names / palette swap.  (Three of these are effectively moot with Enemizer on, and the other is only marginally different and would require me to write branching paths in ShuffleTrapTiles for basically everything which I really don't want to do.)
I've completely re-did the way formations are generated, which should produce far fewer (if any) crashes, since I programmed it in a way to be a lot more tolerant and to always have some way to generate a formation (most crashes were caused by a list …
=> Enemizer update

FF1Lib/Spellcrafter.cs
Red Wizard can now learn LIFE again (there was a mistake where the Red MAGE could learn LIFE but Wizard was forbidden).
This also bans Ninjas from learning LIFE after promotion if LIFE falls in black magic.
=> Spellcrafter LIFE change

FF1Lib/FF1Rom.cs
I moved FixWarpBug to the list of things the randomizer always does, in order to fix a bug with Spellcrafter w/o Magic Level shuffle.  I don't think there is any reason this should not be automatically done, but if anyone finds a reason to not do the bug fix I can change it to be a spellcrafter/MLshuffle unique thing.
=> Spellcrafter bug fix

FF1Lib/Enemizer.cs, FF1Lib/EnemyFormations.cs, FF1Lib/FF1Rom.cs, FF1Lib/Hacks.cs, FF1Lib/Spellcrafter.cs, FF1Lib/asm/0B_9B0C_SetRunnability.asm, FF1Lib/asm/0F_8740_Unrunnable.asm
Here is the preliminary work I've done on splitting the unrunnables.  It has not been thoroughly tested.  At the moment it includes a test of the feature by changing the domain around Coneria to include formation 00 and formation 80 (00's b-side) and sets the b-side to unrunnable.  I believe the romhack portion works fine, but I have not thoroughly tested the changes I made to other randomizer features to ensure compatibility.
Additionally, ShuffleUnrunnables now checks the formations it cycles through with foreach, and if they were unrunnable normally (either with vanilla stats or with the formation generator's alterations), ShuffleUnrunnables will create that many unrunnables on the A-Side.  On the B-Side, all formations except the fiend fights are included in the shuffle.  This will …
=> Splitting Unrunnables

FF1Blazorizer/Pages/Randomize.cshtml, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs
Turn open progression into two flags; Extended Open is dependent only on the Southern Continent Edits and not the Northern Docks
=> Split Docks out from Open Prog

FF1Blazorizer/Pages/Randomize.cshtml, FF1Blazorizer/wwwroot/presets/beginner.json, FF1Blazorizer/wwwroot/presets/chaos-rush.json, FF1Blazorizer/wwwroot/presets/debug.json, FF1Blazorizer/wwwroot/presets/default.json, FF1Blazorizer/wwwroot/presets/full-npc.json, FF1Blazorizer/wwwroot/presets/improved-vanilla.json, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs
- Adds a new flag, 'FixMissingBattleRngEntry', a boolean which defaults to false, under the Experimental randomizer section.
- New code in FF1Rom.cs attempts to insert the hex value '95' into the battleRng list
- For all boilerplate code, I attempted to copy formatting exactly.
- Only added to the Blazorizer app. MainWindow.xaml and all old-site preset files have been ignored.
Reviewer recommendations:
1. Check syntax for correctness and functionality, especially `FF1Rom.cs`, which was something of a stab in the dark. Submit review with corrections.
2. Once corrected syntax is in this PR, test both viewing the Blazorizer app and generating a ROM from this branch.
3. If those look OK, push to Alpha and I will test out that playing through various generated ROMs with the flag on show no …
=> Add experimental flag to patch the missing hex value in the Battle RNG table

FF1Lib/Enemizer.cs, FF1Lib/Spellcrafter.cs
Three changes in this pack:
- Spellcrafter now excludes damage spells that are too weak from being assigned to spellcasting items
- NULL spells can now be learned by any character that would be able to learn spells at a given level
- WarMECH's name now changes based on the image of the enemy.  For example, an IMP picture will give you the WarIMP.  WarMECH's traits otherwise will always be the same.
=> Small Enemizer and Spellcrafter tweaks

FF1Blazorizer/Pages/Randomize.cshtml, FF1Blazorizer/Shared/ClampedSlider.cshtml, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/EnemyFormations.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Scale.cs
Moved weapon bonuses to before weapon doubling. This should cause weapons to receive 1 full crit% per bonus instead of .5
=> Moved weapon bonuses to before weapon crit doubling

FF1Lib/Enemies.cs, FF1Lib/Enemizer.cs
Enemizer Changes:
- Pattern tables are now shuffled, which means that monster types that couldn't appear together in vanilla can appear together in Enemizer.
- Garland, Astos, and Pirates are all locked to their vanilla appearances.
- Vampire encounter is now drawn like other boss battles, except with the enemy replacing Vampire being drawn (instead of a random enemy with the Vampire graphic).
=> More OFD Stuff

FF1Lib/Enemizer.cs
Now, large enemies have a higher chance of rolling a higher damage tier, and late-game enemies no longer receive a boost to attack power.
=> Minor change to Enemizer

FF1Blazorizer/Pages/Randomize.cshtml, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/ItemMagic.cs
Balanced Item Magic Shuffle is implemented.  Rather than use the Spellcrafter methods and structures, we simply remove spells which fit particular criteria as being too strong or too weak.  Any item can carry any spell, and there are no guarantees of certain magics appearing, unlike in Spellcrafter.  This feature is compatible with Spellcrafter as well.
=> Balanced Item Magic Shuffle

FF1Lib/Spellcrafter.cs
Tier 6 MUDL no longer paralyzes.  It is simply confusion (and thus, enemies will no longer castt it).
=> Minor fix to Spellcrafter

FF1Lib/ShardHunt.cs
Four NPCs are checking at the old location for the Earth Orb for their dialog tree, so we update it to the new location.
=> Fix NPC dialog because of ShiftEarthOrbDown

FF1Lib/FF1Rom.cs
This should fix the issue with NPC Guillotine removing the Rod and Lute plates.  The way it works is that it changes the plates to "Talk_ifitem" and rewrites the map object data so that both results return dialogue 0xFF (the "you sense something evil?" text).
=> NPC Guillotine bugfix

FF1Lib/Enemizer.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs
If "Only Shuffle Bosses" or "Generated New and Balanced Scripts" are turned on, Enemizer will know that it is allowed to create new scripts for spellcasting monsters ("Wz" type monsters and status-elemental enemies).
Team Steak is disabled when generating new enemies (Enemizer), since the Tyro image in pattern tables is moved around.
Generate New and Balanced Scripts now no longer only checks the Medusa script for repeats, so it can be used with Enemizer without producing wonky results.
=> Minor Enemizer fix

FF1Lib/Enemizer.cs, FF1Lib/ItemMagic.cs, FF1Lib/Magic.cs
- Balanced Item Magic Shuffle no longer includes evasion spells with more than 80 effectivity, or armor spells with more than 32 effectivity.  Balanced Item Magic Shuffle no longer includes resistance spells which resist all elements.  This removes WALL from the vanilla spell pool, and INV8/FOG8/WAL8 from the Spellcrafter spell pool plus some other spells.
- Tiered Magic Shuffle is less likely to land tier 7-8 spells in the first 6 slots (chance reduced to 5% for 1-3 and 15% for 4-6) and more likely to land tier 4-6 spells in the first 3 slots (chance increased from 20 to 25%, with 15% likelihood of landing in 7-8).
- Flans in Enemizer have a 50% chance of rolling 255 absorb.  This is one of the few enemy class specific rules I want to bring back, the other being class specific crit rates …
=> Minor tweaks to Item Magic Shuffle, Enemizer, and Tiered Magic Shuffle

FF1Lib/Weapon.cs
No weapon will possess more than 50 hit rate (fixes an overflow issue with very high level Ninjas).
A better fix would have to reinstate the cap or change the way weapons add to hitrate.
=> Weapon Blurse fix

FF1Blazorizer/Pages/Randomize.cshtml, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Enemizer.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Scale.cs
Included an option to make the Pirates much more buff - each pirate's stats are around those of a level 6 Fighter, and the xp/gold reward is increased by a factor of 20 (800 gold/xp per pirate).
=> Swole Pirates Fun Hack

FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Weapon.cs
Updated random weapon bonuses to be 3 crit per bonus instead of two. Updated the tooltip to reflect this change.
This should make weapons a bit more effective as end game options, as well as making a -5 masmune a less appealing.
=> Random Weapon Bonus Balance Changes

FF1Blazorizer/Pages/Randomize.cshtml
There have been numerous comments on the discord that this button is ambiguous in meaning. It also confusingly matches the wording of the menu button which selects this page. Changing it to "Generate ROM" states the precise action it accomplishes.
=> Renaming "Randomize" button to "Generate ROM"

FF1Blazorizer/Pages/Randomize.cshtml, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Fun.cs, FF1Lib/Preferences.cs
The DoMagicFlash function it works by setting the palette for the background to the palette of the spell being cast on alternating frames.
Removing this is done by changing the swap color of the spell to the current background itself. It should take up the same number of frames as the original, when it goes to swap it'll just swap to itself.
=> Added a fun% flag for removing the spell cast flash from casting spells.

FF1Lib/Magic.cs
Mixed spellbooks (vanilla) no longer shuffles the original magic list, instead shuffling a temp list.  This should fix an issue with confuse not working properly.
=> Mix Spellbooks fix

FF1Blazorizer/Pages/Randomize.razor
The new Randomize.razor wasn't allowing players to select Buy 10 (old) due to some error.  It has been fixed with this.
=> Buy 10 (old) fix

FF1Blazorizer/Pages/Randomize.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/asm/0E_95AE_DoClassChange-2.asm, FF1Lib/asm/0E_95AE_DoClassChange.asm, FF1Lib/asm/1E.asm, FF1Lib/asm/1E_85B0_DoPartyGen_OnCharacter.asm
**Pool Party**
Change party creation at the start of the game. It fills a pool with random characters, allowing duplicates, from which to form the party. Once a character is selected, it's removed from the pool. Cancelling your choice puts back the character in the pool.
Key points:
- Modify extensively DoPartyGen_OnCharacter
- Use an array of 10 bytes in memory which isn't used at party creation, tests didn't bring up any problems
- Ignore Party Composition flags for now, but it's possible to take them into accounts down the road. Works fine with Tavern Recruitment.
**Random Class Change**
Promote party to random classes.
Key points:
- Modify extensively DoClassChange, doesn't break "Nones"
Flags are in experimental section
=> Pool Party + Random Class Change

FF1Blazorizer/Pages/Randomize.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/asm/1B_8FF5_GameOverAndRestart.asm
SaveWhenGameOver fixes
Fix a bug with SaveWhenGameOver that would revives Nones when reloading a game; also change the main routine so has to not fiddle with NPC flags as much.
Key points:
- Change from checking various NPC flags to checking which battle killed the party.
- Restore Astos to normal behaviour without allowing to cheat his item.
SuffleAstos
Shuffle Astos script to a random key NPC, as is he's hiding as this new NPC.
Key points:
- Compatible with SaveWhenGameOver
- If Astos is Bahamut, there's substantial change to Astos's routine and SaveWhenGameOver
=> ShuffleAstos and SaveWhenGameOver fix

.circleci/deploy.sh
This is up for feedback right now only, and to see what netlify does with this as a PR, it should just deploy the standard thing with nothing changing.
The intent of this change is to create new sites each time we deploy the main site.
So when www.finalfantasyrandomizer.com updates to version 5.23.1, we create 5-23-1.finalfantasyrandomizer.com and deploy the exact same build there. A possible additional change that I am thinking about including is the flag decoding, it should check the version only for the versioned and live site, but the sha for alpha and beta sites. This would allow for minor updates that do not affect flags or rng to each version after it is deployed.
=> Versioned deploys

FF1Blazorizer/Tabs/BugFixesTab.razor, FF1Blazorizer/wwwroot/presets/Anti_Double_Bingo.json, FF1Blazorizer/wwwroot/presets/Beginner.json, FF1Blazorizer/wwwroot/presets/Chaos_Rampage.json, FF1Blazorizer/wwwroot/presets/Chaos_Rush.json, FF1Blazorizer/wwwroot/presets/Entrance_Floor_Shuffle.json, FF1Blazorizer/wwwroot/presets/Improved_Vanilla.json, FF1Blazorizer/wwwroot/presets/Shard_Hunt.json, FF1Blazorizer/wwwroot/presets/default.json, FF1Lib/BugFixes.cs, FF1Lib/ChanceToRun.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/presets/beginner.json, FF1Lib/presets/debug.json, FF1Lib/presets/default.json, FF1Lib/presets/full-npc.json, FF1Lib/presets/improved-vanilla.json, Sandbox/TreasureDistribution.cs
A niche flag for challenge flagsets where you don't get to choose your classes. It overrides the class specific run chances with a fixed one.
Done to make things like Solo WM more bearable.
=> ChanceToRun

FF1Blazorizer/Tabs/FunTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json
I was looking at all of the new options and what they do and noticed that some tooltips could use some TLC. I scrubbed each tooltip, cleaning up grammar, formatting, and spelling, trying to get some consistency across all of the tooltips. Deleted a duplicate tooltip entry. Placed tooltip objects in order with their associated tabs and groups. Updated references to portrayals in screenshots where appropriate.
Changed "Mapman" to "Map Character" in the Fun% tab.
=> Clean up tooltip grammar/spelling, change mapman

FF1Lib/Fun.cs
An ode to FF5's terrible PS1 translation, which conveniently uses the same number of letters as "WYVERN":
=> Add "Y BURN" to Fun Enemy Names

FF1Blazorizer/Tabs/FileTab.razor, FF1Lib/Helpers/Utilities.cs
I found a bug in my handling of downloading spoiler logs when attempting to get a spoiler log that is empty (i.e. not using the Treasures flag). This PR fixes that by ensuring the `SpoilerCache` is initialized with an empty string. Additionally, I added logic to the File Tab to not download a spoiler log if the `SpoilerCache` is empty and display a message stating as much to the user.
=> [Bugfix] Set default SpoilerCache value and check for empty string

FF1Blazorizer/Shared/CheckBox.razor, FF1Blazorizer/Shared/TriStateCheckBox.razor
This will allow users to right-click on a tristate checkbox to cycle the opposite direction. If a tristate is checked and the user wants to clear it, rather than click it twice, they only need to right-click once.
- Adds a `preventDefault` flag for the `oncontextmenu` event AND an event handler that does nothing as well, as both are required to prevent the context menu from appearing. I don't know why `preventDefault` didn't work on it's own, but Today I Learned... 🤷‍♂️
- Changed from `onclick` to `onmouseup` because blazor also doesn't seem to care about `MouseEventArgs` when provided, despite the docs saying that it does... 🤷‍♂️
- Did the same thing with regular checkboxes so that people can't inadvertently attempt to back cycle on them and then have a context menu appear and the box …
=> All backward cycling through tristate checkboxes

FF1Blazorizer/Shared/CheckBox.razor, FF1Blazorizer/Shared/TriStateCheckBox.razor
Adds click event handlers to the labels for the checkboxes so that they can interpret left and right mouse button clicks after my change to make the tristate boxes multidirectional.
=> Add handler to checkbox labels to make clickable again

FF1Lib/FF1Rom.cs, FF1Lib/Interfaces.cs, FF1Lib/ItemPlacement.cs, FF1Lib/Maps.cs, FF1Lib/OverworldMap.cs
Shard and loose incentive item placement now filters on accessibility before placement, so if a flag makes a chest completely inaccessible, it won't result in a soft lock.
=> If floater is removed, don't include Cardia entrances in E/F shuffle.

FF1Lib/ItemPlacement.cs
This fixes a major placement bug in the previous logic:
The floater would get placed as a loose item, progression items would
get placed on the basis of assumed access to the airship, but after
sane placement was complete, the the floater was replaced with a dud
item (cabin), making progression impossible.
This removes the floater entirely, prior to placement, as intended.
=> Replace floater in unincentivizedQuestItems list when IsFloaterRemoved

.circleci/deploy.sh, FF1Blazorizer/wwwroot/index.redirect.html
The goal of this proposed change is to ensure stable URLs by always
sending the user to an instanced site.  This way, when the user copies
a link out of the URL bar to share with others, they get a stable URL.
1) instanced master deploy is the same x-y-z.ffr.com
2) beta site now deploys as beta-(commit).ffr.com
3) ffr.com and beta.ffr.com front page deploy a simple index.html with
a meta refresh redirect to the most recently deployed instanced site.
=> Improve versioned deployment to get more stable URLs

.circleci/deploy.sh, FF1Blazorizer/Tabs/FileTab.razor, FF1Blazorizer/Tabs/FunTab.razor, FF1Blazorizer/wwwroot/_headers, FF1Blazorizer/wwwroot/index.html, FF1Blazorizer/wwwroot/index.redirect.html, FF1Blazorizer/wwwroot/js/prefframe.js, FF1Blazorizer/wwwroot/js/site.js, FF1Blazorizer/wwwroot/preferences.html
Workaround for the issue that every instanced site has its own separate local storage, and thus its own separate preferences.
Uses an iframe to load a stub page at a single domain which can then save and load key-value data.  The domain where preferences get stored is determined by where the iframe is loaded from.
done: preferences and the ROM data
todo: convert presets to this scheme.
=> Save preferences and ROM data at a single domain.

FF1Lib/Hacks.cs
Improves format/readability of class permissions as well.
Fixed the text size check, the text starts at 0xA000 has 0x1000 bytes
allocated, because the new chest opening routines start at 0xB000
=> Eliminate unnecessary whitespace to avoid spilling into 0xB000

FF1Lib/DeepDungeon.cs
There was a bug causing the Gaia shortcut flag to modify Onrac's map due to deep dungeon swapping their map indexes. This simply creates a new list for assigning town map indexes to teleporters instead of actually swapping the maps around, so now all the town map modifications should work.
=> Fixes Gaia shortcut in deep dungeon

FF1Blazorizer/Tabs/ClassesTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Classes.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/asm/1B_9830_LevelUp_MPUp.asm
Lets the user restore charges from leveling up. When they get a max mp in a spell level, they will also get a current mp in that same spell level.
They also have the option of having it enabled for all classes, only promoted classes, or as a class blessing.
=> Added an option for spellcaster's spell charges to restored on max mp up.

FF1Blazorizer/Tabs/QoLTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Fun.cs, FF1Lib/Preferences.cs, FF1Lib/asm/UninterruptedMusic-QoLFlag.asm
Adds a new QoL Flag which changes the standard treasure sound effect so it no longer resets the music every time you open a chest.
=> Uninterrupted Music

FF1Lib/Maps.cs
Nothing can fit there normally, and it breaks short ToFR
=> Remove Chaos floor from chest relocation

FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs
call FightBahamut before RelocateChests
corrects edge case where Bahamut floor chests might be inaccessible (trapped behind dragon NPCs)
=> fix relocateChests w/ FightBahamut

FF1Blazorizer/Tabs/ShopsTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/LegendaryShops.cs
Fix Spellcrafter + Legendary Shop bug that could dupe spells and wasn't pulling HEALs
Remove PURE & SOFT from the normal Legendary Shop pool (they are re-added when White & Item shops are both exclusive)
Add XFER and HEL2 to the pool
Add tooltips for White/Black Legendary Magic Shops explaining vanilla spells available
Made LOCK/LOK2 pool-inclusion dependent on the LOCK Buff flag
=> Legendary Shops: Replace PURE/SOFT w/ XFER/HEL2; fix Spellcrafter pool bug; add tooltips

FF1Lib/ItemGenerator.cs, FF1Lib/ItemLists.cs
Makes Opal Helm & Gauntlets Rare instead of Legendary.
Makes Power Gauntlet Legendary instead of Rare.
Makes Power Staff Rare instead of Common.
Adjusts generated wealth/shop ratios to match changes.
=> Tweak Equipment Tiers

FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/DeepDungeon.cs, FF1Lib/Enemies.cs
Fix Randomized Touch never giving Death/Stone Touch
Added "Balanced Rude" Touch Pool ( Death, Stone, and Mute comparatively more likely, Dark less likely)
=> Bugfix Randomized Touch, new "Balanced Rude" Pool

FF1Blazorizer/Tabs/ShopsTab.razor, FF1Blazorizer/wwwroot/presets/Beginner.json, FF1Blazorizer/wwwroot/presets/Chaos_Rush.json, FF1Blazorizer/wwwroot/presets/Deep_Dungeon.json, FF1Blazorizer/wwwroot/presets/Entrance_Floor_Shuffle.json, FF1Blazorizer/wwwroot/presets/Floaterless.json, FF1Blazorizer/wwwroot/presets/Free_Enterprise.json, FF1Blazorizer/wwwroot/presets/Hidden_Chaos.json, FF1Blazorizer/wwwroot/presets/Improved_Vanilla.json, FF1Blazorizer/wwwroot/presets/Lichs_Revenge.json, FF1Blazorizer/wwwroot/presets/NOverworld.json, FF1Blazorizer/wwwroot/presets/Oops_All_Loose.json, FF1Blazorizer/wwwroot/presets/Over_Randomizer.json, FF1Blazorizer/wwwroot/presets/Procgen_Overworld.json, FF1Blazorizer/wwwroot/presets/Shard_Hunt.json, FF1Blazorizer/wwwroot/presets/coop2022.json, FF1Blazorizer/wwwroot/presets/default.json, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/ExtConsumables.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Magic.cs
Life in Battle can now be set to LIFE1 + LIFE2, to LIFE1 (and Phoenix Down) Only, or to Off.
Also fixed a bug where Life in Battle wouldn't work properly for Life2 Spell Crafter effects that weren't named "LIF2" (they're usually LIF7 or LIF8).
=> 'Life in Battle' Sub-option for Only Life1

FF1Blazorizer/Tabs/IncentivesTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/IncentiveData.cs, FF1Lib/Interfaces.cs, FF1Lib/ItemLocations.Lists.cs, FF1Lib/Maps.cs
Clarifies where random incentives are more clearly by naming them specifically instead of using a generic "Gating" terminology.
Adds a Random Deep/Shallow option for Volcano.
Fixes Mermaid Prison + Sea Shrine Locked Incentive.
Cleans up redundant tooltips.
=> 'gating' cleanup plus volcano deliniation

FF1Lib/Armor.cs, FF1Lib/Weapon.cs
Fix: WALL wasn't generating in Weaponizer or Armor Crafter correctly
Fix: Armor Crafter Black Shirt was pulling from the White Shirt defensive spell pool instead of the intended damage-spell pool
=> Armor Crafter/Weaponizer Spell Bugfixes

FF1Lib/Party.cs
If a Forced Class at character select can't find any valid classes, it'll now only randomize amongst unpromoted classes
=> Forced Giving Promoted Fix

FF1Lib/ItemMagic.cs, FF1Lib/StartingEquipment.cs
Fixed: Curated Item Magic Pool + All Weapons Cast Spells not filling fully
Fixed: Random Starting Caster Items not caring about Randomized Item Magic Pools
Cleanup: Starting Caster or Caster AoE Items now always dynamic rather than hard-coded
Fixed: No Legendary Duplicates mostly not working with non-vanilla sets
=> Bugfixes & Cleanup for Item Magic Pools & Starting Caster Items

FF1Blazorizer/Tabs/QoLTab.razor, FF1Lib/FF1Rom.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Fun.cs, FF1Lib/Hacks.cs, FF1Lib/Preferences.cs, FF1Lib/asm/0B_99C8_FixRespondRate.asm
Instead we replace the value at the point where it is read. Instead of reading from the respond rate byte we read a hardcoded value which is written by the randomizer.
=> LockRespondRate: Add a slider which controls the respond rate.

FF1Blazorizer/FF1Blazorizer.csproj, FF1Blazorizer/Tabs/ExperimentalTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/asm/1B_9900_SetRNG.asm
In this flag:
The RNG pointer will not advance per frame.
The RNG pointer for a battle will start at a location that is determined in such a way:
For a random encounter it will start at the random encounter battle number multiplied by  a constant + the formation multiplied by a constant.
For a boss or spiked tile encounter it will start at the formation number multiplied by a constant.
From there each turn will have an RNG start point that is derived from the battle start RNG.
=> Added SetRNG to randomizer as a beta flag.

FF1Blazorizer/Tabs/ClassesTab.razor, FF1Lib/Transmooglifier.cs
- Improved White Mage Harm will now function with Transmooglifier and apply to a random spellcaster who can cast HARM unpromoted. If none are available it will not be applied. When applied it will be shown in the character's description.
=> Transmooglifier Harm Fix

FF1Lib/Transmooglifier.cs
Fix a bug where Unarmed attack wouldn't show in the status screen if it was the only weapon a class would roll access to (looking at you, Chocobo)
=> Transmooglifier Unarmed Display Fix

FF1Lib/Maps.cs
It was trying to place a chest in a room with no floor space for chests.
=> Fix relocate chests crash on waterfall room group

FF1Lib/Data/ShopData.cs
Fixes an issue causing placement logic to fail when ShopShuffle is disabled.
=> Initialize ItemShopSlot to vanilla location in the ShopData constructor.

FF1Blazorizer/Tabs/ExperimentalTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Flags/Flags.cs, FF1Lib/Randomize.cs, FF1Lib/RngTables.cs, FF1Lib/asm/1F_C571_EncounterPrng.asm
This adds a "true prng" encounter table to the Experimental tab. Overwrites the subroutine that reads from the fixed 256-step encounter table with one that draws from a 16-bit xorshift prng. The rando seeds this prng and chooses one of 4 related prngs, so that it almost never the same with new seeds.
The rng state is stored in sram as soon as party select is confirmed, and persists across hard/soft resets.
=> Adds "true prng" encounter table to Experimental

FF1Blazorizer/Tabs/FileTab.razor, FF1Blazorizer/Tabs/GoalTab.razor
This adds the Archipelago Player Name preference to the File tab. It stays in the Goals tab as well. The primary reason for including it here is that blind flags make the Goals tab inaccessible to edit the player name.
When Archipelago is enabled, a text field opens in the File tab updated with the current Player Name value. Editing in either tab updates the other.
=> Archipelago PlayerName in FileTab

FF1Lib/BankUsageRegister.md, FF1Lib/RngTables.cs, FF1Lib/asm/1F_C571_EncounterPrng.asm
Moved the offending bytes to a new spot and recorded in the register.
=> Bugfix for true RNG clobbers transmoog data

FF1Lib/ResourcePack.cs, FF1Lib/Sprites.cs
This adds NPC sprite import via resource pack. Here's a reference image for the sprite sheet.
Shopkeepers along the top, followed by 28 npc sprites (leaving out orb and plate sprites, which are coded as npcs and stored with them in the ROM). Vanilla palettes applied; uses grayscale to match pixels to palette values, as with enemy sprite imports. NPC sprites use magenta to indicate transparent, as with mapman sprites.
Tested with npc recruitment flags -- since the sprite replacements happen before any of the randomizing, the recruitable class sprites show up fine.
=> NPC sprite import via resource pack
