FiendsOfTheElements/FF1Randomizer

FF1Lib/Fun.cs, FF1Lib/Hacks.cs
Adjusted multi-level patch to not auto-advance if there is no controller input.  This makes the patch function more like the original game.
'Disable Music' functionality also added to the music randomizer.
=> Adjusted multi-level patch

FF1Lib/Hacks.cs
By popular demand. Now he minds his own business out of the way.
=> Relocate the annoying Elfland elf.

FF1RandomizerOnline/Views/Home/Randomize.cshtml, FF1RandomizerOnline/wwwroot/js/site.js
Because I'm salty at running the wrong seed.
=> Add an import function, supporting crim_bot generated seed/flag strings.

FF1RandomizerOnline/Views/Home/Randomize.cshtml, FF1RandomizerOnline/wwwroot/js/site.js
This one is not only against dev, it also updates the sliders. \o/
=> Add import function, supporting native's copy/paste syntax to WWW.

FF1Lib/Credits.cs
I was wrong - this is just fine.
=> Put some credits back in!

FF1Lib/FF1Rom.cs
MeridianBC's patch and my patch overlapped a bit and luckily just
broke one meaningless thing (to our knowledge).
=> Fix clobbered code from double merge.

FF1Lib/Treasure.cs, FF1Lib/asm/0E_92D0_BikkeAnyItem.asm, FF1Lib/asm/0E_9356_StandardNPCItemTrade.asm
=> Npc shuffle critical fixes

FF1RandomizerOnline/Views/Home/Randomize.cshtml
=> Disable UI checkboxes instead of hiding them based on other flags

FF1Lib/BugFixes.cs, FF1Lib/Credits.cs, FF1Lib/Enemies.cs, FF1Lib/EnemyFormations.cs, FF1Lib/FF1Rom.cs, FF1Lib/FF1Text.cs, FF1Lib/Flags.cs, FF1Lib/Hacks.cs, FF1Lib/ItemLocations.cs, FF1Lib/ItemPlacement.cs, FF1Lib/Items.cs, FF1Lib/OverworldMap.cs, FF1Lib/Treasure.cs, FF1Lib/asm/0F_8740_Unrunnable.asm, FF1Lib/asm/0F_8960_DrawSeedAndFlags.asm, FF1Lib/asm/0F_8A00_FastBattleBoxes.asm, FF1RandomizerOnline/Controllers/HomeController.cs, FF1RandomizerOnline/Views/Home/Randomize.cshtml
- On top of latest NPC shuffle fixes
- Fix enemy elemental resistances +Flag
- Fix BB Absorb bug +Flag
- Shuffle Enemy formation unrunnability and RUN->WAIT convenience (+2 Flags)
- Shuffle Enemy formation surprise chance (+Flag)
- Shuffle Enemy formation frequency (+Flag)
- Update hash to use MD5 and in game symbols
=> Pre-merged Dev branch

FF1RandomizerOnline/Views/Home/Randomize.cshtml, FF1RandomizerOnline/Views/Home/WhatsNew.cshtml
Be more explicit about just what is and is not accessible without the Mystic KEY.
=> Keyless ToFR Documentation Clarification.

README.md
Fixed some spelling and grammar errors.
=> Fix spelling and grammar in the Readme file.

FF1Lib/ItemPlacement.cs
The shop item was being removed in the wrong spot, and potentially
twice, but not when it came from the treasurePool. That's actually
when the failure occured because there would be too many items and
not enough locations.
=> Non-incentivized shop fix.

FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/Hacks.cs, FF1Lib/presets/beginner.json, FF1Lib/presets/debug.json, FF1Lib/presets/default.json, FF1Lib/presets/finals.json, FF1Lib/presets/full-npc.json, FF1Lib/presets/improved-vanilla.json, FF1Lib/presets/normal-npc.json, FF1Lib/presets/ro16.json, FF1Lib/presets/ro8.json, FF1Lib/presets/semifinals.json, FF1Lib/presets/tournament.json, FF1RandomizerOnline/Views/Home/Randomize.cshtml, FF1RandomizerOnline/Views/Home/WhatsNew.cshtml
Welcome to No Dan Zone, which is probably the easiest thing I have ever written. I didn't include an ASM file because it's "change a number and shove in a whole bunch of well-placed EAEAEAEA".
=> Now introducing: No Dan Mode (aka Static EXP Distribution)

FF1Lib/FF1Rom.cs, FF1Lib/MapGenerator.cs, FF1Lib/Maps.cs, FF1Randomizer/MainWindowViewModel.cs
It's a little rough and a little Magic Number-y, but it's working!
=> Bespoke Waterfall Creation

FF1Lib/FF1Rom.cs, FF1Lib/Hacks.cs, FF1Lib/asm/1E.asm, FF1RandomizerOnline/Views/Home/Randomize.cshtml
Implement the changes Dr. Cat Doctor made to the PartyGen code and change the address that the No Dan mode code is placed
=> Fix PartyGen bug and No Dan Mode 

FF1RandomizerOnline/wwwroot/js/site.js
Incentive Counter updated to now correctly include the Incentive Titan.
=> Quick incentive counter bugfix

FF1Lib/BugFixes.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1RandomizerOnline/Views/Home/Randomize.cshtml
LOCK and LOK2 no longer check if they should hit, they always do now no matter what 
(so long as the enemy is alive)
=> Lock and Lok2 balance changes

FF1Blazorizer/Pages/Randomize.cshtml, FF1Lib/Scale.cs
https://github.com/aspnet/Blazor/issues/1661
=> fix Math.Round bug

FF1Lib/procgen/WaterfallEngine.cs
Fixed a few bugs with the Waterfall Engine (leading to OOB access)
=> Fixed some issues with the Waterfall Engine

FF1RandomizerOnline/Views/Home/Randomize.cshtml, FF1RandomizerOnline/wwwroot/js/site.js
Adds a warning when WarMECH mode is "Unleashed" and encounters have shuffled rarity or are shuffled across all zones.
=> Warmech warning

FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/Interfaces.cs, FF1Lib/ItemPlacement.cs, FF1Lib/OverworldMap.cs, FF1Lib/Treasure.cs, FF1Lib/ViewModelFlags.cs, FF1Lib/presets/beginner.json, FF1Lib/presets/debug.json, FF1Lib/presets/default.json, FF1Lib/presets/full-npc.json, FF1Lib/presets/improved-vanilla.json, FF1Randomizer/MainWindow.xaml, FF1RandomizerOnline/Views/Home/Index.cshtml, FF1RandomizerOnline/Views/Home/Randomize.cshtml, FF1RandomizerOnline/Views/Home/WhatsNew.cshtml
=> 2.5.1 Softlaunch with Free Canal.

FF1Blazorizer/Pages/Randomize.cshtml, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Scale.cs, FF1Lib/Shops.cs, FF1Lib/presets/beginner.json, FF1Lib/presets/debug.json, FF1Lib/presets/default.json, FF1Lib/presets/full-npc.json, FF1Lib/presets/improved-vanilla.json
Magic Shop location shuffle! All the fun of Magic Shop Shuffle, but without the pain of wondering if that spell is Red Wizard learnable or not
=> Shop loc shuffle

FF1Lib/FF1Rom.cs, FF1Lib/Scale.cs
seeliefae's Progressive Orb/Shard XP implementation
=> Orb (or Shard) based Progressive XP

FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Enemizer.cs, FF1Lib/Spellcrafter.cs
Updates tooltip for "Halve BB Crit Rate" to correctly describe the new functionality.
=> Minor tooltip update + Enemizer/Spellcrafter minor update

FF1Blazorizer/Pages/Randomize.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Enemizer.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/Treasure.cs, FF1Lib/asm/1B_8FF5_GameOverAndRestart.asm
I have a list of changes ready for testing.  They still need to be checked for potential errors, so I'm going to wait a bit on adding them to the alpha, but some more eyes would be helpful.  These changes do a few things:
- Save Game When Game Over: When the party wipes, the game is saved (with necessary conditions to prevent players from accidentally softlocking or cheating story battles like Garland and Astos).  NPCs which trigger a fight will always have a condition unrelated to the battle that determines whether they will be reset to visible.  If the player has the airship, they will respawn where they parked the airship and the ship will be moved to Coneria.  If the player has the ship but not the airship, they will respawn where they last docked the ship.  If the player has neither, …
=> Multiple Changes

FF1Blazorizer/Pages/Randomize.razor, FF1Blazorizer/Shared/PartyCompositionClasses.razor, FF1Blazorizer/wwwroot/css/site.css
=> Componentizing and improving party composition section

FF1Lib/FF1Rom.cs
I think I'm probably over complicating this, but it should work.
=> use the seed and flags for rng

FF1Blazorizer/Pages/Randomize.razor, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/IncentiveData.cs, FF1Lib/Interfaces.cs
I added the ability to select the Katana to be added to the incentive item pool.
=> Added an IncentiveKatana

FF1Blazorizer/Tabs/FileTab.razor, FF1Lib/FF1Rom.cs
Only show .nes files in the file selector, check the rom's header and run it through the AssureSafe function on selection
=> Provide more details about the rom and what might be wrong with it

FF1Lib/Data/StartingItems.cs, FF1Lib/Helpers/MemTable.cs, FF1Lib/StartingInventory.cs
* try fixing unsafe code
* use a byte array
=> Fixing unsafe code

.vscode/settings.json, README.md
Previously our README documented features, and honestly no one read it. It was outdated and documented mainly the 2.x release.
I've rewritten the README to help new developers get started, and included the basic git information needed for working with multiple repos.
I initially was going to include information about git bisect, but thought that might be too advanced/niche to include here.
=> Rewrite the README to be developer focused

FF1Lib/EnemyFormations.cs, FF1Lib/Maps.cs
"error CS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)"
=> Fix typecasting error

FF1Lib/BugFixes.cs, FF1Lib/RandomizedClass.cs, README.md
Switches a few functions in BugFixes.cs over to using ReadClassData()
and WriteClassData().
=> Refactor reading ClassData from RandomizeClass to be usable elsewhere

FF1Lib/Maps.cs
use this one, it's history is less noisy I actually branched off dev /facepalm
=> bugfix: fightBahamut: remove Bahamut encounter properly

FF1Blazorizer/Pages/Resources.razor
repair blursed classes link
add jat2980 instructions for Emotracker
add seeliefae tracker
=> fix broken link; add FF1R emotracker and seeliefae tracker

FF1Blazorizer/Tabs/ExperimentalTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/asm/1F_D077_Speedboat.asm
Double the speed of the ship, so it is the same speed as the airship.
=> Speedboat.  Speedboat?  Speedboat!

FF1Lib/ItemPlacement.cs
Adjust item placement so LooseExcludePlacedDungeons does not apply to
shards.  This fixes a couple of problems:
1) Shards will be placed anywhere, instead of only non-incentive
locations (which sharply limited shard placement in a way that was not
intended.)
2) Fixes a crash when LooseExcludePlacedDungeons is enabled along with
every incentive item, every incentive location, and shard
hunt -- because previously, there would be more shards+loose items to
place than available non-incentive locations).
=> Place shards separately from leftoverItems

FF1Blazorizer/Shared/DoubleSlider.razor, FF1Blazorizer/Tabs/ExperimentalTab.razor, FF1Blazorizer/Tabs/ItemEquipmentTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/StartingLevels.cs
Tested with nones gain xp, tavern mode, starting levels. Blame some guy named Wote for the suggestion.
=> Added a max level slider for all the masochistic players.

FF1Blazorizer/Tabs/BlindSeedTab.razor, FF1Blazorizer/Tabs/FileTab.razor, FF1Blazorizer/Tabs/PresetsTab.razor, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Randomizer/MainWindow.xaml.cs, Sandbox/Performance.cs
Please suggest better wordings for the warnings.
Perhaps a better layout to display the warnings is needed.
=> warnings for json loading

FF1Blazorizer/Tabs/ExperimentalTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/Lockpicking.cs, FF1Lib/RandomizedClass.cs, FF1Lib/asm/1B_9300_LockpickDoors.asm
Added a flag to let thieves open locked doors once they reach the required level. The thief can be anywhere in the party.
View 1B_9300_LockpickDoors.asm for more details.
=> Added thief lockpicking flags.

FF1Blazorizer/Tabs/FunTab.razor, FF1Lib/FF1Rom.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/Preferences.cs
Since we already have a player with motion sensitivity, i think this should be added, so they can play along hte same seeds, but slower.
=> Slow Hacks

FF1Blazorizer/Pages/ResAltFiends.razor, FF1Blazorizer/Pages/ResFlags.razor, FF1Blazorizer/Pages/Resources.razor
Alt Fiends page and Old Flagsets page
=> Page Updates for Resources

FF1Blazorizer/Pages/ResAltFiends.razor, FF1Blazorizer/Pages/ResFlags.razor, FF1Blazorizer/Pages/Resources.razor
* Page Updates for Resources
* Update ResAltFiends.razor
page name updated
* Update ResFlags.razor
Page name updated
=> Page Updates for Resources (#655)

FF1Blazorizer/Tabs/ItemEquipmentTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/ItemLists.cs, FF1Lib/ListRNGExtensions.cs, FF1Lib/StartingEquipment.cs
Added a flag for a starter pack of equipment: gives 4 random common weapons, 4 random buyable armors (1 fighter, 1 rm, 2 mage).
Added a flag for a random weakness targeting weapon (not xcal).
=> Added new starting equipment flags

FF1Blazorizer/wwwroot/index.html, FF1Blazorizer/wwwroot/js/prefframe.js, FF1Blazorizer/wwwroot/js/site.js
In case there's a race between the parent loading and the preferences
iframe loading.
=> When the iframe finishes loading, it posts a message to the parent.

FF1Blazorizer/wwwroot/index.html, FF1Blazorizer/wwwroot/js/prefframe.js, FF1Blazorizer/wwwroot/js/site.js
Just keep pinging the iframe until we get an answer.
=> Try the brute force solution for preference loading.

FF1Lib/Armor.cs, FF1Lib/Hacks.cs, FF1Lib/Weapon.cs
Tested with shopinfo / equip screen info / chest info
=> Add class permissions to weapon/armor info

FF1Blazorizer/Tabs/ItemEquipmentTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/Interfaces.cs, FF1Lib/ItemPlacement.cs, FF1Lib/Weapon.cs
Should have done this a long time ago. Those pesky bane swords and thor hammers are a real thorn in my side ;-)
=> oops no item magic

FF1Blazorizer/Tabs/AdjustmentsTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs
=> quick minimap load

FF1Lib/DeepDungeon.cs, FF1Lib/Fun.cs
Changes Astos to submarine girl in the lobby and CROWN to OXYALE in the dungeon. Also changes the dialogue of the other NPCs to mention verbally what floor they skip to.
=> Changed Astos to Submarine girl in DD lobby

FF1Lib/DeepDungeon.cs
Allows deep dungeon to create some floors as "grid style" with layout similar to Marsh basement or the mermaid floor of the Sea Shrine
=> New style of floor for deep dungeon

FF1Blazorizer/Tabs/OverworldTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/MapExchange/OwMapExchange.cs, FF1Lib/OverworldMap.cs, FF1Lib/procgen/NewOverworld.cs, FF1R/Commands/Procgen.cs
Also rework the different procgen map options into one enum.
=> Fix map generate/import producing different seeds.

FF1Lib/ShardHunt.cs
fix off by one; now creates valid asm for orbs check during Talk_BlackOrb
=> fix specific orbs glitch

FF1Lib/FF1Rom.cs, FF1Lib/Fun.cs
WzOgre →Grover (from Sesame Street)
WzVAMP → Edward (from Twilight)
R.GOYLE →ARGYLE (sounds similar)
R.Ankylo →FunPolic (from DW1R)
WzMUMMY →MOMMY (someone has to be in charge)
BADMAN →Batman (I always think this when I see them)
EVILMAN →OKAYMAN (name moved over)
Whether to capitalize names or not is confusing
=> Add some new fun% enemy names

FF1Lib/PredictivePlacement.cs
=> nolooseinincentives bug

FF1Blazorizer/Tabs/ShopsTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/BugFixes.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Hacks.cs, FF1Lib/ItemMagic.cs, FF1Lib/Magic.cs
Tournament Item magic Pool
Lower Thief Agility Settings
Buff Tier1 Damage Spells
=> Various stuff

FF1Lib/Enemies.cs, FF1Lib/FF1Rom.cs, FF1Lib/Hacks.cs, FF1Lib/Scale.cs
Swole bahamut gets a nastier slate of spells.
=> Bahamut is scaled like a boss.

.circleci/deploy.sh, FF1Blazorizer/Pages/About.razor, FF1Blazorizer/Pages/Index.razor, FF1Blazorizer/Shared/AnnouncementBox.razor, FF1Blazorizer/Shared/MainLayout.razor, FF1Blazorizer/Shared/NavMenu.razor, FF1Blazorizer/Tabs/PresetsTab.razor
Change "Resources" link to "Wiki"
Update discord invite link
This can be merged.
=> Linking to wiki

FF1Blazorizer/Tabs/QoLTab.razor, FF1Blazorizer/Tabs/ScaleTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/FF1Rom.cs, FF1Lib/FlagsViewModel.cs, FF1Lib/Fun.cs, FF1Lib/ItemMagic.cs, FF1Lib/Preferences.cs
Mutes the sfx when walking over lava tiles; Requested by Serisan.
=> New "Disable Damage Tile SFX" QoL Flag

FF1Blazorizer/wwwroot/presets/Beginner.json, FF1Blazorizer/wwwroot/presets/Chaos_Rush.json, FF1Blazorizer/wwwroot/presets/Deep_Dungeon.json, FF1Blazorizer/wwwroot/presets/Entrance_Floor_Shuffle.json, FF1Blazorizer/wwwroot/presets/Floaterless.json, FF1Blazorizer/wwwroot/presets/Free_Enterprise.json, FF1Blazorizer/wwwroot/presets/Hidden_Chaos.json, FF1Blazorizer/wwwroot/presets/Lichs_Revenge.json, FF1Blazorizer/wwwroot/presets/NOverworld.json, FF1Blazorizer/wwwroot/presets/Oops_All_Loose.json, FF1Blazorizer/wwwroot/presets/Over_Randomizer.json, FF1Blazorizer/wwwroot/presets/Procgen_Overworld.json, FF1Blazorizer/wwwroot/presets/Shard_Hunt.json, FF1Blazorizer/wwwroot/presets/default.json, FF1Lib/Scale.cs
Seen multiple people interested in something between 5% and 10%.  (Due to the way the scaling is handled, 7.5% exactly wasn't available, so I went with the closest option.)
=> 7.7% Progressive Scaling Option

FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/DeepDungeon.cs, FF1Lib/FF1Rom.cs, FF1Lib/Maps.cs
Random is weighted.
Should be compatible with Deep Dungeon.
=> More Warmech Modes - All & Random

FF1Lib/FlippedMaps.cs
=> fix flip waterfall

FF1Blazorizer/Pages/Randomize.razor, FF1Blazorizer/Tabs/ExperimentalTab.razor, FF1Blazorizer/Tabs/GoalTab.razor, FF1Blazorizer/Tabs/ShopsTab.razor, FF1Blazorizer/wwwroot/presets/Beginner.json, FF1Blazorizer/wwwroot/presets/Chaos_Rush.json, FF1Blazorizer/wwwroot/presets/Deep_Dungeon.json, FF1Blazorizer/wwwroot/presets/Entrance_Floor_Shuffle.json, FF1Blazorizer/wwwroot/presets/Floaterless.json, FF1Blazorizer/wwwroot/presets/Free_Enterprise.json, FF1Blazorizer/wwwroot/presets/Hidden_Chaos.json, FF1Blazorizer/wwwroot/presets/Improved_Vanilla.json, FF1Blazorizer/wwwroot/presets/Lichs_Revenge.json, FF1Blazorizer/wwwroot/presets/NOverworld.json, FF1Blazorizer/wwwroot/presets/Oops_All_Loose.json, FF1Blazorizer/wwwroot/presets/Over_Randomizer.json, FF1Blazorizer/wwwroot/presets/Procgen_Overworld.json, FF1Blazorizer/wwwroot/presets/Shard_Hunt.json, FF1Blazorizer/wwwroot/presets/default.json, FF1Blazorizer/wwwroot/tooltips/tooltips.json, FF1Lib/Archipelago.cs, FF1Lib/FF1Rom.cs, FF1Lib/Flags.cs, FF1Lib/FlagsViewModel.cs
Rename Beta Tab to Experimental
Combine Free Clinic and Clinics Heal Statuses flags; move to Shop Tab
Move AP to Goals Tab
Fix Presets
=> Experimental Tab Stuff

FF1Lib/Classes.cs
=> Fix No Promo Armor malus accidentally blocking other things that can be in the malus list

FF1Blazorizer/Tabs/ClassesTab.razor, FF1Blazorizer/Tabs/ItemEquipmentTab.razor, FF1Blazorizer/wwwroot/tooltips/tooltips.json
=> reorder blursings/transmoog; add tooltip

FF1Lib/Transmooglifier.cs
Expected Chance of Causing Bugs or Impacting other features: **None**
- Spellcasters will no longer low roll into 0 Max MP
- Non-spellcasters will no longer be given 2 MP at start sometimes
Note: Visual studio has also decided to add a bunch of whitespace to some lines, only three lines of code actually impacted.
=> Transmooglifier MP Fixes

FF1Lib/AltFiends.cs, FF1Lib/Bahamut.cs, FF1Lib/Credits.cs, FF1Lib/DesertOfDeath.cs, FF1Lib/Enemies.cs, FF1Lib/Enemizer.cs, FF1Lib/FF1Rom.cs, FF1Lib/Fun.cs, FF1Lib/Hacks.cs, FF1Lib/Helpers/FF1Pointer.cs, FF1Lib/LichsRevenge.cs, FF1Lib/NpcHints.cs, FF1Lib/Randomize.cs, FF1Lib/ResourcePack.cs, FF1Lib/StatsTracking.cs
This fixes many accumulated bugs in resource pack loading, in preparation for enemy sprite and enemy name resource pack options.
1. Split the resource pack loader into two: one adds to the vanilla ROM before all the data is read and stored in the various data structures; this was needed for proper maptile import. The other does everything else after ROM expansion; this is necessary because some of the sprite and text mods work with that extra space. 
2. Added a more automatic enemy name reader and writer that consolidates the process. This also takes advantage of some empty ROM space, putting 64 names in the new place and 64 names in the usual spot; pointers to names are written automatically as well. This way all names can potentially have the max 8 characters without worry about running …
=> Small updates and bugfixes to resource pack import and stats tracking

FF1Lib/StatsTracking.cs
Fixes a bug where status window was tracking luck instead of evade%
=> Bug Fix: Status stats track luck instead of evade
